### ISSUE TITLE
Questions about dataset

### ISSUE THREAD

**Issue by Cyunon** [Shawnxm/EMP#2]
I ran into some problems with the dataset while reproducing your work. I would like to know some details of "type", "object ID", "object model" and those "-1" in ego_object, or if you can provide some examples of these data for reference. At the same time I want to know the role of the data in the "order" folder. Looking forward to your reply！

**Comment by Shawnxm** [comment]
Thanks for the questions.
- `type` means the class of an object (same as "type" in KITTI dataset), such as "Car", "Cyclist", "Pedestrian", etc.
- `object ID` is a unique ID assigned to an object in the game.
- `-1` columns in `ego_object` are actually meaningless. As mentioned in the description, `ego_object` files have the same format as augmented labels (`label_2_aug`). Some columns are set to `-1` because a vehicle cannot get certain information for itself. For example, one cannot see itself in its own camera data, so it cannot get the 2D bounding box (`2d bbox`) information.
- `order` folder contains text files to indicate the presence of each frame in different vehicles' data. It is created for our EMP prototype where each vehicle instance uses such information to learn when to load sensor data to emulate real-world data collection. Vehicles may miss some frames. For example, an order file named 0004354.txt containing text "1\n1\n\n\n1\n1\n..." (`\n` means new line) means: Vehicle 4354 has frames 0, 1, 4, 5, ...

I would suggest you check our [DeepGTAV-PreSIL](https://github.com/Shawnxm/DeepGTAV-PreSIL) repo for more information on how the dataset is collected. Specifically, [ObjectDetection.cpp](https://github.com/Shawnxm/DeepGTAV-PreSIL) contains key functions used to generate different types of data.

**Comment by Cyunon** [comment]
Thank you very much for your reply and I will go to check the DeepGTAV-PreSIL repo.
